fix: Rectified the incorrect tuple value
hirosystems/explorer pull request #1166
Opened 2023-06-12 21:23 UTC by shamim-io

closes [ https://github.com/hirosystems/explorer/issues/1156 ]

Closes Incorrect display of optional in tuple result #1156

Fixes issue: Incorrect display of optional in tuple result 

Feature details
Rectified the incorrect tuple value

Feature image
<img width="622" alt="Screenshot 2023-06-13 at 2 52 41 AM" src="https://github.com/hirosystems/explorer/assets/29030948/a9de8569-d744-4acb-b7c6-5ada9330bb6e">

2023-06-13 17:16 UTC, He1DAr commented on src/components/function-summary/value.tsx
> +    if (arg?.name?.includes('ustx')) {
I suggest we remove the optional operator `?` whenever possible. It looks like it used to expect arg to always exist.

2023-06-13 17:16 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +    if (item?.type?.includes('list')) {
Same for this one

2023-06-13 17:17 UTC, He1DAr commented
Thank you for the PR @shamim-io! Left a few comments, please let me know if you have any questions.

2023-06-16 13:18 UTC, He1DAr commented
Sure! https://explorer.hiro.so/txid/0x87844d48c19a0664fd8f270f247e6e4c29b7f72e895d7ab9572c9bc246f5867f?chain=testnet

2023-06-18 09:28 UTC, shamim-io commented
@He1DAr I have updated the PR. Please check!

2023-06-21 21:07 UTC, He1DAr requested changes
Awesome work @shamim-io! Left a few comments.

2023-06-21 21:07 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +    return typeof reprValue === 'object' ? JSON.stringify(reprValue) : reprValue.toString();
Please try to avoid calling `toString` for the list case as it's already a string. A similar implementation like existing one should do the trick.

2023-06-21 21:07 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +  const getReprValue = (item: any) => {
Please add typing to function argument and unit tests.

2023-06-21 21:07 UTC, He1DAr commented on src/components/function-summary/value.tsx
> +const isJSONString = (str: string) => {
I suggest we move this to utility file and add a unit test.

2023-06-21 21:07 UTC, He1DAr commented on src/components/function-summary/value.tsx
> +const getValue = (arg: any, btc: null | string) => {
Please add typing to function argument.

2023-06-21 21:07 UTC, He1DAr commented on src/components/function-summary/value.tsx
> +const getValue = (arg: any, btc: null | string) => {
Please add unit tests to `getValue` function that cover both cases (arg.repr is/isn't json).

2023-06-26 13:42 UTC, shamim-io commented
@He1DAr I have updated the PR by adding typings and test cases wherever possible. However, there are components that still lack test cases. In those cases, I have refrained from writing a test case for a small function to avoid duplicating efforts. Instead, we need to create a test file for the entire component.

2023-06-28 19:51 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +    let reprValue = value ?? 'none';
I would add `.toString();` to the value here to match the old code. This part is pretty sensitive to changes.

2023-06-28 19:51 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +  const getReprValue = ({ type, value }: ReprValueProps) => {
I believe this function can be defined outside the component.

2023-06-28 19:52 UTC, He1DAr commented on src/components/function-summary/value.spec.ts
> +import { getValue } from './value';
Thank you for adding tests!

2023-06-28 19:52 UTC, He1DAr commented on src/components/function-summary/result.tsx
> +      reprValue = value.map((listEntry: any) => listEntry.value).join(', ');
would be great if we eliminate this remaining `any`

2023-06-28 19:53 UTC, He1DAr commented
> @He1DAr I have updated the PR by adding typings and test cases wherever possible. However, there are components that still lack test cases. In those cases, I have refrained from writing a test case for a small function to avoid duplicating efforts. Instead, we need to create a test file for the entire component.

Sounds good! Thank you for adding tests. I left a few tiny comments. Great work @shamim-io!

2023-09-20 14:35 UTC, merged

2023-09-20 14:36 UTC, blockstack-devops commented
:tada: This PR is included in version 1.123.0 :tada:

The release is available on [GitHub release](https://github.com/hirosystems/explorer/releases/tag/v1.123.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: