Feature: Added transaction icons
hirosystems/explorer pull request #1181
Opened 2023-06-19 18:24 UTC by shamim-io

closes [ https://github.com/hirosystems/explorer/issues/1122 ] #1122 

Feature details
Added transaction icons

Feature image
<img width="449" alt="Screenshot 2023-06-19 at 11 51 45 PM" src="https://github.com/hirosystems/explorer/assets/29030948/c182a74f-6f62-4aaf-ba29-4f662fa54e81">

2023-06-21 21:10 UTC, He1DAr requested changes
Thank you so much for fixing this @shamim-io! Left a tiny nit

2023-06-21 21:10 UTC, He1DAr commented on src/ui/icons/CoinbaseIcon.tsx
> +'use client';
Could you please use coinbase icon from react-icons?

2023-06-21 21:10 UTC, He1DAr commented on src/ui/icons/PoisonMicroblockIcon.tsx
> +'use client';
We could also use cube icon from react-icons for this one.
<img width="335" alt="image" src="https://github.com/hirosystems/explorer/assets/97111756/1c4e91f4-788b-4ffe-babe-60cc784e786b">

2023-06-26 13:46 UTC, shamim-io commented
@He1DAr I can change the icons and use react-icons. But as per this comment: [ https://github.com/hirosystems/explorer/issues/1122#issuecomment-1592064076 ], provided figma file, and specification to use the dimension as 16 * 16. I think we might have to use the svg. 

Can you please confirm that once. Thanks!

2023-06-29 15:06 UTC, He1DAr commented
@shamim-io We're good to use react-icons for now. Thank you @shamim-io!

2023-09-20 14:29 UTC, merged

2023-09-20 14:30 UTC, blockstack-devops commented
:tada: This PR is included in version 1.122.0 :tada:

The release is available on [GitHub release](https://github.com/hirosystems/explorer/releases/tag/v1.122.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: