fix: time on mobile view
hirosystems/explorer pull request #1231
Opened 2023-07-13 12:52 UTC by dragnoir

Close [#997](https://github.com/hirosystems/explorer/issues/997)

I used the [hover media](https://drafts.csswg.org/mediaqueries/#hover) query to display the full time on devices with touch screen (not able to hover)

** On Desktop **
<img width="428" alt="image" src="https://github.com/hirosystems/explorer/assets/12425932/e86ef8f3-9078-4379-8093-853cad28231b">

** On Tablet **
<img width="487" alt="image" src="https://github.com/hirosystems/explorer/assets/12425932/e7009fd7-08f8-4480-9fe2-2c59a05c8da3">

2023-07-14 12:57 UTC, andresgalante commented
I love this type of contribution that help with accessibility. 

Thanks @dragnoir 🙏

2023-07-14 13:31 UTC, He1DAr requested changes
Thank you for the PR! Left a tiny comment.

2023-07-14 13:31 UTC, He1DAr commented on src/app/txid/[txid]/TxDetails/BlockHeight.tsx
> +import { useMediaQuery } from '@chakra-ui/react'
Could you please wrap `useMediaQuery` under /ui directory similar to the rest of ChakraUI components instead of using it directly?

2023-07-25 22:04 UTC, He1DAr approved these changes

2023-07-25 22:09 UTC, He1DAr commented
@dragnoir Great work! Could you please fix linting so we ship it?

2023-07-26 19:16 UTC, dragnoir commented
@He1DAr linting fixed.

2023-07-28 20:16 UTC, merged

2023-07-28 20:17 UTC, blockstack-devops commented
:tada: This PR is included in version 1.110.5 :tada:

The release is available on [GitHub release](https://github.com/hirosystems/explorer/releases/tag/v1.110.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: