fix(0x): applied style fix at app lvl
hirosystems/explorer pull request #1724
Opened 2024-07-09 22:09 UTC by BLuEScioN

2024-07-10 15:17 UTC, hugocaillard reviewed
Thanks for looking into this @BLuEScioN.
Genuine question about this fix:
Is it worth wrapping the _whole_ page in an extra `div`?
Couldn't the theme be change to add this prop to the `body` or an existing wrapper?

I don't know much about this repo or emotion, so that's really a naive question

2024-07-11 17:52 UTC, BLuEScioN commented
> Thanks for looking into this @BLuEScioN. Genuine question about this fix: Is it worth wrapping the _whole_ page in an extra `div`? Couldn't the theme be change to add this prop to the `body` or an existing wrapper?
> 
> I don't know much about this repo or emotion, so that's really a naive question

Good idea. I just combined the flex and styledwrapper

2024-07-15 15:01 UTC, He1DAr requested changes
Could you update the commit message to follow the Conventional Commits specification?

2024-07-16 16:53 UTC, He1DAr approved these changes

2024-07-16 19:20 UTC, merged

2024-07-16 19:20 UTC, blockstack-devops commented
:tada: This PR is included in version 1.190.4 :tada:

The release is available on [GitHub release](https://github.com/hirosystems/explorer/releases/tag/v1.190.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: