fix(cycle-start-block): done
hirosystems/explorer pull request #1726
Opened 2024-07-10 21:03 UTC by BLuEScioN

Addresses https://github.com/hirosystems/explorer/issues/1714

![image](https://github.com/hirosystems/explorer/assets/20312835/b000ca69-b18f-4a6a-b46f-4002b7e1a9d0)

2024-07-10 21:04 UTC, BLuEScioN commented
@eugeniadigon 
Thoughts on having two lines to display both the prepare and reward phase information?

2024-07-11 08:58 UTC, eugeniadigon commented
> @eugeniadigon Thoughts on having two lines to display both the prepare and reward phase information?

Looks good to me 👍

2024-07-15 15:06 UTC, He1DAr requested changes
Could you update the commit message to follow the Conventional Commits specification?

2024-07-16 16:53 UTC, He1DAr approved these changes

2024-07-16 19:21 UTC, merged